# -*- coding: utf-8 -*-

STRING_EMPTY = ""
STRING_SPACE = " "
STRING_PLAIN_ENTER = "\r\n"
STRING_HTML = "html"
STRING_BUSINESS_NAME = "business_name"
STRING_ACCOUNT_TYPE = "account_type"
STRING_RELEASE_DATE = "release_date"
STRING_TEAM = "team"
STRING_TEAM_CONTACT = "team_contact"

STRING_FORMAT_3 = "{0}{1}{2}"
STRING_FORMAT_FULL_SECOND = "%Y-%m-%d %H:%M:%S"
STRING_FORMAT_FULL_MINUTE = "%Y-%m-%d %H:%M"
STRING_FORMAT_FULL_MICRO_SECOND = "%Y-%m-%d %H:%M:%S,%f"
STRING_FORMAT_NO_HYPHEN = "%Y%m%d"

STRING_COL_ORG_NAME = "查询企业名称"
STRING_COL_QUERY_TIME = "查询时间"
STRING_COL_KEYWORD_COUNT = "关键字数量"
STRING_COL_BUSINESS_ID = "机构id"
STRING_COL_BUSINESS_NAME = "机构名称"
STRING_COL_USER_ID = "用户id"
STRING_COL_USER_NAME = "用户名称"
STRING_COL_QUERY_COUNT = "搜索记录总次数"
STRING_COL_REGISTRATION_COUNT = "登记笔数"
STRING_COL_FILE_COUNT = "文件数"
STRING_COL_PAGE_COUNT = "页数"
STRING_COL_ACCOUNT_TYPE = "开通账户类别"
STRING_COL_RELEASE_DATE = "开通时间"
STRING_COL_TEAM = "所属团队"
STRING_COL_TEAM_CONTACT = "团队对接人"




